# 项目-wide Gradle 设置。
# IDE (例如 Android Studio)
# 对于如何配置 Gradle 构建环境的更高级设置，请参考
# http://www.gradle.org/docs/current/userguide/build_environment.html

# 指定用于守护进程的 JVM 参数
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# 当启用后，Gradle 会优先于已构建的依赖项从新的/未构建的子项目中使用包含的依赖项
android.useAndroidX=true
# 启用非传递性 R 类生成
android.nonTransitiveRClass=true
